<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="92278" started-at="2019-03-02T08:22:54Z" finished-at="2019-03-02T08:24:27Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="92278" started-at="2019-03-02T08:22:54Z" finished-at="2019-03-02T08:24:27Z">
      <class name="com.testpackage.LoginpageMyntraTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.testpackage.LoginpageMyntraTest@3ac3fd8b]" name="setup" is-config="true" duration-ms="14285" started-at="2019-03-02T08:23:57Z" finished-at="2019-03-02T08:24:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="title()[pri:1, instance:com.testpackage.LoginpageMyntraTest@3ac3fd8b]" name="title" duration-ms="10" started-at="2019-03-02T08:24:12Z" finished-at="2019-03-02T08:24:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- title -->
        <test-method status="PASS" signature="loginmyntra()[pri:2, instance:com.testpackage.LoginpageMyntraTest@3ac3fd8b]" name="loginmyntra" duration-ms="15017" started-at="2019-03-02T08:24:12Z" finished-at="2019-03-02T08:24:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginmyntra -->
      </class> <!-- com.testpackage.LoginpageMyntraTest -->
      <class name="com.testpackage.HomepageMyntraTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.testpackage.HomepageMyntraTest@43a25848]" name="setup" is-config="true" duration-ms="42702" started-at="2019-03-02T08:22:54Z" finished-at="2019-03-02T08:23:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="mentshirt()[pri:0, instance:com.testpackage.HomepageMyntraTest@43a25848]" name="mentshirt" duration-ms="19666" started-at="2019-03-02T08:23:37Z" finished-at="2019-03-02T08:23:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mentshirt -->
        <test-method status="FAIL" signature="verify_title()[pri:0, instance:com.testpackage.HomepageMyntraTest@43a25848]" name="verify_title" duration-ms="24" started-at="2019-03-02T08:23:57Z" finished-at="2019-03-02T08:23:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Online Shopping for Women, Men, Kids Fashion & Lifestyle - Myntra] but found [Men T-shirts - Buy T-shirt for Men Online in India | Myntra]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Online Shopping for Women, Men, Kids Fashion & Lifestyle - Myntra] but found [Men T-shirts - Buy T-shirt for Men Online in India | Myntra]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testpackage.HomepageMyntraTest.verify_title(HomepageMyntraTest.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_title -->
      </class> <!-- com.testpackage.HomepageMyntraTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
